services:
  - type: web
    name: noob
    plan: free
    env: docker
    dockerfilePath: Dockerfile
    repo: https://github.com/greenhornet63603/noob
    branch: main
    autoDeploy: false
    envVars:
      - key: 8396814092:AAHtUGEPciF5LdiCo572-TczY3EZwx0Otis
        sync: false
      - key: 27400172
        sync: false
      - key: 56d0a75c5f9a9de6beb5452aa63c2d36
        sync: false
      - key: 7540570087
        sync: false
      - key: noob
        sync: false
      #- key: WEBHOOK
        #sync: false
      - key: PORT
        value: 8000  # Default port value, update if needed
